[TRRFFDA-513] Allow Conditional Rendering to support CDEs being used for multiple show/hides
eresearchqut/trrf pull request #161
Opened 2020-02-04 07:56 UTC by alintreznai

2020-02-05 11:20 UTC, sztamas requested changes

2020-02-05 11:20 UTC, sztamas commented on rdrf/rdrf/forms/dsl/parse_operations.py
>              return len(my_cdes - other_cdes) == 0
Why isn't this `my_cdes == other_cdes`?
What if `my_cdes` is a subset of `other_cdes`?

2020-02-05 11:20 UTC, sztamas commented on rdrf/rdrf/forms/dsl/parse_operations.py
>          return hash((self.action, ))
Why isn't this `return hash(self.action)` instead?

2020-02-05 18:41 UTC, alintreznai commented on rdrf/rdrf/forms/dsl/parse_operations.py
>              return len(my_cdes - other_cdes) == 0
Updated to `self.target_cdes == other.target_cdes` and implemented `__eq__/__hash__ `for EnrichedCDE. They need to be equal so don't need to check for one being the subset of another.

2020-02-05 18:42 UTC, alintreznai commented on rdrf/rdrf/forms/dsl/parse_operations.py
>          return hash((self.action, ))
Indeed. Probably was a copy-paste from other `__hash__` implementations. Updated.

2020-02-06 05:22 UTC, sztamas approved these changes

2020-02-06 05:22 UTC, merged