[TRRFFDA-542] Users cannot register on IOS
eresearchqut/trrf pull request #166
Opened 2020-02-11 02:54 UTC by ScriptSmith

2020-02-11 03:54 UTC, ScriptSmith commented
The `is_mobile` stuff in registration could perhaps be organised a bit better so that this sort of situation doesn't happen again. Perhaps a global variable in the JS would indicate whether it's in a mobile context, and then we can make decisions in the control flow, rather than by adding bits and pieces of JavaScript in the template.

2020-02-11 07:02 UTC, sztamas requested changes

2020-02-11 07:02 UTC, sztamas commented on rdrf/rdrf/templates/registration/registration_base.html
> +            {% if not is_mobile %}
I agree with your comment that the mobile special cases should be handled nicer than this.

What I would do here is create a function

```javascript

    function expandAccordion(formSelector) {
        if (! $(formSelector).length ) {
            return;
        }
        var accordion = $(formSelector).accordion("instance");
        if (typeof(accordion) === "undefined") {
            return;
        }
        accordion.option("active", 0);
    }
```

and then call it from `onBeforeSubmit()` like so:

```javascript
    expandAccordion("#patient-form");
    expandAccordion("#guardian-form");
```

`expandAccordion` would expand only if the form exists and accordion has been set up on it, which is what we really care about (not tying the decision to the special case of `is_mobile`)

2020-02-12 05:15 UTC, sztamas approved these changes

2020-02-12 08:57 UTC, merged