[CDAP-26] Locate and upgrade outdate JS files
eresearchqut/trrf pull request #218
Opened 2020-04-08 02:27 UTC by ScriptSmith

I've removed a lot of unused JS files that had been left in the repository, or that were included in some templates but not actually used. I'll create a table with a full accounting of the removed and updated dependencies for this PR, so that we can debug any breaking changes. If you see any other unused dependencies, please let me know.

The `js_dependencies.py` script creates a package.json and bower.json that can be scanned by github, and dependabot. This works successfully as seen here in the [sec-adv-test repo](https://github.com/eresearchqut/sec-adv-test). It picked up all the vulnerabilities identified by the security testers + one more for jquery-ui.

I renamed and moved vendored js dependencies in order for them to be picked up by this script, and match a package name + version in npm or bower.

If we're happy with the way this is done, I can move on to actually updating the depenencies.

2020-04-08 02:48 UTC, ScriptSmith commented
And I used the following to find the js files we were using:

```
find rdrf/rdrf/templates/ -name "*.html" | xargs cat | python -c 'from bs4 import BeautifulSoup; import sys; [print(script.get("src")) for script in BeautifulSoup("\n".join([line for line in sys.stdin])).findAll("script", {"src": True})]' | sort | uniq
```

2020-04-09 07:45 UTC, ScriptSmith commented
# Change summary
|Name|Type|                                       Change                                                                    |
|----------------|---------------------------------|--------------------------------------------------------------------|
|`ie_select`|JS dep|Removed dependency and references in template|
|`dynamic_formsets_plugin`|JS file|Removed file and references in template|
|`toggle_disabled`|JS file|Removed file and references in template|
|`generic_validator`|JS file|Removed file and references in template|
|`jquery-userTimeout`|JS dep|Moved file and updated references in template|
|`html5shiv`|JS dep|Removed dependency and associated templates|
|`theme.js`|JS file|Removed file and associated templates|
|`d3.js`|JS dep|Removed dependency|
|`nv.d3`|Dep|Removed dependency|
|`myts.ts`|TS file|Removed file|
|`jquery-bootgrid`|Dep|Removed dependency|
|`password.js`|JS file|Removed file|
|`flipclock`|Dep|Removed dependency and associated template|
|`gallery.js`|JS file|Removed file|
|`jquery-isotope`|Dep|Removed dependency|
|`sketch`|JS dep|Removed dependency|
|`imagesloaded`|JS dep|Removed dependency|
|`codemirror`|JS dep|Removed dependency and reference in template
|`bootstrap 4`|Dep|Removed dependency|
|`jquery-userTimeout`|Js Dep|Replaced with minified js|
|`bootstrap 3`|Dep|Updated in vendor dir and changed references|
|`bootstrap slider`|Dep|Moved to vendor dir and changed references|
|`datatables`|Dep|Moved to vendor dir and changed references|
|`timepicki`|Dep|Moved to vendor dir and changed references|
|`chart.js`|Js Dep|Renamed and changed references|
|`flexslider`|Dep|Removed dependency|
|`jquery-time-duration-picker`|Js Dep|Renamed and changed references|
|`jsignature`|Js Dep|Updated changed references|
|`moment`|Js Dep|Updated and changed references|
|`adsafe`|Js Dep|Renamed and changed references|
|`jquery-validation`|Js Dep|Updated and changed references|
|`jquery`|Js Dep|Updated and changed references|
|`jquery-ui`|Dep|Updated and changed references|

2020-04-14 05:05 UTC, sztamas requested changes
Just a few minor things worth mentioning and then this one is good to go!

2020-04-14 05:05 UTC, sztamas commented on scripts/js_dependencies.py
> +        exit(changed)
This should be `sys.exit`, `exit` is to be used in the interactive shell, not in programs.

2020-04-14 05:05 UTC, sztamas commented on scripts/js_dependencies.py
> +    sorted_deps = sorted(deps, key=lambda d: d[0])
Just as a python tip: you could use `key=itemgetter(0)` instead of the lambda (from the `operator` module).

2020-04-14 05:05 UTC, sztamas commented on scripts/js_dependencies.py
> +            "dependencies": {name: version for name, version in sorted_deps}
that's just `dict(sorted_deps)`?

2020-04-14 05:05 UTC, sztamas commented on scripts/js_dependencies.py
> +    else:
You can drop the `else` and unindent the rest. One advantage of shortcutting functions as you did above is that you reduce the nesting.

2020-04-14 05:31 UTC, ScriptSmith commented on scripts/js_dependencies.py
> +    sorted_deps = sorted(deps, key=lambda d: d[0])
Cool, thanks!

2020-04-14 05:38 UTC, sztamas approved these changes

2020-04-14 05:40 UTC, merged