Implement form with validation for Parent's Add Patient functionality
eresearchqut/trrf pull request #366
Opened 2021-09-27 02:00 UTC by ppettitau

2021-09-27 05:20 UTC, ScriptSmith requested changes

2021-09-27 05:20 UTC, ScriptSmith commented on rdrf/registry/patients/admin_forms.py
> +    country = forms.ChoiceField(required=True, widget=(CountryWidget()), choices=CountryWidget.choices(), initial="")
The brackets around `CountryWidget` are redundant, as is calling it

2021-09-27 05:20 UTC, ScriptSmith commented on rdrf/rdrf/templates/rdrf_cdes/parent.html
>          function not_implemented() {
`not_implemented` can be removed

2021-09-27 05:20 UTC, ScriptSmith commented on rdrf/registry/patients/parent_view.py
> +        use_parent_address = form_clean['use_parent_address']
It's arguably more Pythonic to write this fragment like so:

```python
        address_fields = {
            "patient": patient,
            "address_type": address_type
        }
        if form_clean['use_parent_address']:
            address_fields.update({
                "address": self.parent.address,
                "suburb": self.parent.suburb,
                "state": self.parent.state,
                "country": self.parent.country,
                "postcode": self.parent.postcode,
            })
        else:
            address_fields.update({
                "address": form_clean["address"],
                "suburb": form_clean["suburb"],
                "state": form_clean["state"],
                "country": form_clean["country"],
                "postcode": form_clean["postcode"],
            })

        PatientAddress.objects.create(**address_fields)
```

Or don't bother with dictionary and just call `create` in either circumstance

And because we're still on Python 3.8 and don't have [dictionary union operators](https://www.python.org/dev/peps/pep-0584/)

However I don't really mind the current syntax, so happy to keep it as it is. Just FYI

2021-09-27 05:20 UTC, ScriptSmith commented on rdrf/registry/patients/parent_view.py
> +        return self._render_parent(request, registry_code, ParentAddPatientForm())
What's the purpose of moving this to its own method?

2021-09-27 05:23 UTC, ppettitau commented on rdrf/registry/patients/admin_forms.py
> +    country = forms.ChoiceField(required=True, widget=(CountryWidget()), choices=CountryWidget.choices(), initial="")
Oops. Good pick up, will remove.

2021-09-27 05:23 UTC, ppettitau commented on rdrf/rdrf/templates/rdrf_cdes/parent.html
>          function not_implemented() {
Will remove.

2021-09-27 05:23 UTC, ppettitau commented on rdrf/registry/patients/parent_view.py
> +        return self._render_parent(request, registry_code, ParentAddPatientForm())
I call it again when the form is invalid in post()

2021-09-27 05:26 UTC, ppettitau commented on rdrf/registry/patients/parent_view.py
> +        use_parent_address = form_clean['use_parent_address']
Yep, I'll have a look. The logic here was just existing code that moved around with my changes but I'm happy to refactor it while I'm here.

2021-09-27 05:26 UTC, ScriptSmith commented on rdrf/registry/patients/parent_view.py
> +        return self._render_parent(request, registry_code, ParentAddPatientForm())
Ah yep, missed that :smile:

2021-09-27 05:31 UTC, ScriptSmith commented on rdrf/registry/patients/parent_view.py
> +        use_parent_address = form_clean['use_parent_address']
All good, the current way is more concise so I kind of prefer it, even if it's a bit repetitive.

2021-09-28 22:41 UTC, ppettitau commented on rdrf/registry/patients/admin_forms.py
> +    country = forms.ChoiceField(required=True, widget=(CountryWidget()), choices=CountryWidget.choices(), initial="")
Done

2021-09-28 22:41 UTC, ppettitau commented on rdrf/rdrf/templates/rdrf_cdes/parent.html
>          function not_implemented() {
Done

2021-09-28 22:42 UTC, ppettitau commented on rdrf/registry/patients/parent_view.py
> +        use_parent_address = form_clean['use_parent_address']
Done

2021-09-28 23:48 UTC, ScriptSmith commented on rdrf/registry/patients/admin_forms.py
> +    country = forms.ChoiceField(required=True, widget=(CountryWidget()), choices=CountryWidget.choices(), initial="")
Calling `CountryWidget` is still redundant, the convention when setting the widget is to just use the class name like so:

```python
country = forms.ChoiceField(required=True, widget=CountryWidget, choices=CountryWidget.choices(), initial="") 
```

Unless you need to set some properties of the widget, which doesn't apply in this case

2021-09-29 07:04 UTC, ppettitau commented on rdrf/registry/patients/admin_forms.py
> +    country = forms.ChoiceField(required=True, widget=(CountryWidget()), choices=CountryWidget.choices(), initial="")
Fixed

2021-09-29 07:05 UTC, ScriptSmith approved these changes

2021-09-30 22:05 UTC, merged