ERE-1876] Add form position saving
eresearchqut/trrf pull request #487
Opened 2022-07-28 06:55 UTC by ScriptSmith

2022-07-29 04:55 UTC, ScriptSmith commented
Still needs some final touches & testing, but I'm interested in feedback on the feature.

I ended up needing to use [InteractionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) rather than traditional APIs because it was proving too difficult to keep track of focus / interaction with the form elements any other way. I hope the support and performance of this is OK, I haven't tried it out on a phone / low-spec device yet.

Likewise I also needed to use [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) because [waiting for the collapse animations to complete](https://github.com/eresearchqut/trrf/pull/487/commits/e111822543eceb4e89b5e2b367fcba0d3e1e5f0a) wasn't enough to initiate the scroll, as the CDE widgets mess with page height as they're being rendered so it would end up scrolling to the wrong place.

Also, the banner being `position: fixed` makes scrolling to a particular element a bit challenging, as if you use the default `scrollIntoView` config, it will put scroll the page so that element is obscured by the banner. Scrolling so that the element is centered seems OK, although it can be a little disorientating still.

I've made the feature optional, because the default behaviour is to collapse all sections on save (unless there are errors). We could consider changing this, but I think it's something angelman needed to quick navigation, so I'm apprehensive about that.

Overall it feels a bit hacky & tacked-on. To do this properly, I think you'd need to submit the form data using JS rather than as a form `POST`, but that would be a much larger change.

2022-08-01 03:29 UTC, ScriptSmith commented
Updated to just focus on interactions with form input elements as suggested by @ppettitau 

Now captures the current position on redirect when a form is saved for the first time.

Also scrolls to a visible ancestor when there are hidden form elements that have events triggered.

As discussed, we could make this the default behaviour, but this has only been requested because of UX in a clinical setting with a couple of large forms, so I think making it optional is best for now.

2022-08-01 04:17 UTC, ppettitau requested changes
Looks like a good solution to a complex problem.

Just had the one question about the save_position label.

2022-08-01 04:17 UTC, ppettitau commented on rdrf/rdrf/models/definition/models.py
> +    save_position = models.BooleanField(default=False, help_text="Return to the current position on form save")
Would this benefit from being a bit more verbose. e.g. "Return the user to their current position on form save"?

2022-08-01 04:17 UTC, ppettitau commented on rdrf/rdrf/templates/rdrf_cdes/form.html
> +                window.history.replaceState(null, null, "?" + searchParams);
Cool, didn't know you could do this.

2022-08-01 04:22 UTC, ScriptSmith commented on rdrf/rdrf/templates/rdrf_cdes/form.html
> +                window.history.replaceState(null, null, "?" + searchParams);
Neither did I :)

2022-08-01 04:23 UTC, ScriptSmith commented on rdrf/rdrf/models/definition/models.py
> +    save_position = models.BooleanField(default=False, help_text="Return to the current position on form save")
Agreed

2022-08-01 04:25 UTC, ppettitau approved these changes

2022-08-01 04:55 UTC, merged