[ERE-1973] Partial Import/Export
eresearchqut/trrf pull request #558
Opened 2023-03-31 05:48 UTC by ppettitau

Partial Import/Export of:
* Context Form Groups
* Forms
* Dashboards

Refactor existing Registry export

2023-04-02 22:00 UTC, ppettitau commented on rdrf/rdrf/exporter_utils.py
> +    response = HttpResponse(yaml_data, content_type='text/yaml')
Looking at the Stack trace information link provided, I don't believe the stacktrace is passed all the way through to this location.

if the exporter returns errors, a different path is followed.

![image](https://user-images.githubusercontent.com/60163872/229381243-4c4fe5cd-4f5f-470b-8dfb-557529642583.png)

2023-04-03 02:56 UTC, ScriptSmith requested changes

2023-04-03 02:56 UTC, ScriptSmith commented on rdrf/rdrf/services/io/defs/exporter.py
> +            return item_name in export_definition
In `_export_cascading_form_definition`:

```python
    return Exporter(registry_model=registry).partial_export({'context_form_groups': context_form_groups,
                                                             'forms': forms,
                                                             'sections': sections,
                                                             'cdes': cdes})
```

`should_export` may return `True`, because a key with a value of `None` is still `in` the dict

2023-04-03 02:56 UTC, ScriptSmith commented on rdrf/rdrf/services/io/defs/importer.py
> +                if "display_name" in frm_map:
`abbreviated_name` doesn't get updated on import, which I believe is because it's missing here (this was probably already a bug)

2023-04-03 02:56 UTC, ScriptSmith commented on rdrf/rdrf/exporter_utils.py
> +    response = HttpResponse(yaml_data, content_type='text/yaml')
Yep, I'm happy to say this is a false positive

2023-04-03 04:04 UTC, ppettitau commented on rdrf/rdrf/services/io/defs/importer.py
> +                if "display_name" in frm_map:
In latest commit, have set this if form wasn't created (e.g. on edit)

2023-04-03 04:04 UTC, ppettitau commented on rdrf/rdrf/services/io/defs/exporter.py
> +            return item_name in export_definition
Have addressed in latest commit

2023-04-03 04:30 UTC, ScriptSmith approved these changes

2023-04-03 04:33 UTC, merged