[ERE-2049] Working Group Types and Rules
eresearchqut/trrf pull request #574
Opened 2023-05-10 05:11 UTC by ppettitau

* Add new models Working Group Type and Working Group Type Rule
* Modify Working Group multi select in Patient, User, and Report Designer forms to use optgroups to provide visual separation where working groups have types.
* Add logic to use newly defined Working Group Type Rule to determine which working groups a user has default access to, under certain circumstances.

2023-05-10 05:16 UTC, ppettitau commented
Need to do:
- [ ] Unit test for `working_group_optgroup_choices` in `rdrf/registry/groups/forms.py`
- [ ] Unit test for `WorkingGroupManager.get_by_user()` in `rdrf/registry/groups/models.py`
- [ ] Potentially rename `WorkingGroupManager.get_by_user()` to something more descriptive of its purpose i.e. `get_by_user_with_type_rules`

2023-05-12 06:58 UTC, ScriptSmith requested changes
From the ticket:

> We can also take this further and add rules for the patients, and then use that to validate their groups on save
> e.g. Patients MUST have a Hospital WG and MUST have a Specific Condition Group WG

Was this considered? Seems like it will be needed eventually.

2023-05-12 06:58 UTC, ScriptSmith commented on rdrf/rdrf/testing/unit/groups_form_tests.py
> +        choices = working_group_optgroup_choices(WorkingGroup.objects.all(), custom_make_option_fn)
Not sure what this is testing. Why does it need a custom fn param, and why test multiple registries?

2023-05-12 06:58 UTC, ScriptSmith commented on rdrf/rdrf/testing/unit/groups_model_tests.py
> +    def setUp(self) -> None:
Return type not being checked so not worth including.

2023-05-12 06:58 UTC, ScriptSmith commented on rdrf/rdrf/testing/unit/groups_model_tests.py
> +        self.assertEqual(list(WorkingGroup.objects.get_by_user(self.user_researcher, apply_type_rules=False)), [self.wg_arrythmia,
The `apply_type_rules` param isn't really useful if it's just used in this assertion. Maybe a feature to test this if it's necessary?

2023-05-14 21:32 UTC, ppettitau commented on rdrf/rdrf/testing/unit/groups_form_tests.py
> +        choices = working_group_optgroup_choices(WorkingGroup.objects.all(), custom_make_option_fn)
It is emulating how the function is used for the Report Designer. 

The custom fn param is required to return a json (similar to the test) to the UI which is then used by the JS to hide/show working groups based on the Registry selected.

2023-05-14 21:35 UTC, ppettitau commented on rdrf/rdrf/testing/unit/groups_model_tests.py
> +        self.assertEqual(list(WorkingGroup.objects.get_by_user(self.user_researcher, apply_type_rules=False)), [self.wg_arrythmia,
I guess it's not currently necessary, I was just trying to think ahead where we could potentially do some refactoring to use this method. I'll remove it for now

2023-05-14 21:44 UTC, ppettitau commented on rdrf/rdrf/testing/unit/groups_model_tests.py
> +    def setUp(self) -> None:
Oops. it was autogenerated and I didn't notice it.

Fixed.

2023-05-14 21:45 UTC, ppettitau commented on rdrf/rdrf/testing/unit/groups_model_tests.py
> +        self.assertEqual(list(WorkingGroup.objects.get_by_user(self.user_researcher, apply_type_rules=False)), [self.wg_arrythmia,
Fixed.

2023-05-14 21:47 UTC, ppettitau commented
> From the ticket:
> 
> > We can also take this further and add rules for the patients, and then use that to validate their groups on save
> > e.g. Patients MUST have a Hospital WG and MUST have a Specific Condition Group WG
> 
> Was this considered? Seems like it will be needed eventually.

Once I got into it, it didn't really feel like it fit in with this feature which is more about assigning default access rather than enforcing requiredness.

2023-05-15 00:19 UTC, ScriptSmith commented on rdrf/rdrf/testing/unit/groups_form_tests.py
> +        choices = working_group_optgroup_choices(WorkingGroup.objects.all(), custom_make_option_fn)
Ah yep, my bad! Missed that :facepalm:.

2023-05-15 00:21 UTC, ScriptSmith approved these changes

2023-05-15 02:49 UTC, merged