[ERE-2157] Check for existing user with email
eresearchqut/trrf pull request #631
Opened 2023-08-04 04:50 UTC by ScriptSmith

2023-08-04 04:54 UTC, ppettitau requested changes

2023-08-04 04:54 UTC, ppettitau commented on rdrf/registry/patients/admin_forms.py
> +                    if CustomUser.objects.filter(email=email).exists():
Should probably do a case insensitive check here i.e. `test@email.com` is the same email as `TEST@email.com`

2023-08-04 05:22 UTC, ppettitau approved these changes

2023-08-07 00:36 UTC, Lexiel46 approved these changes

2023-08-07 00:39 UTC, merged