[ERE-2119] Add "Unsubscribe all" email preference value to reporting
eresearchqut/trrf pull request #632
Opened 2023-08-07 03:49 UTC by Lexiel46

2023-08-07 05:53 UTC, ScriptSmith approved these changes
Looks good. Worth looking at reporting on individual `EmailNotificationPreference`s in a follow-up ticket as well?

2023-08-08 21:59 UTC, ppettitau requested changes
This looks great, well done!

In line with Adam's comment, I think if we want to introduce the other Email Preference details then we should 'future proof' the Unsubscribe All option by nesting it within an `emailPreferences` structure, similar to patient address and working groups, etc. If we released the Unsubscribe All in it's current position and then later refactored it, it would break any existing reports that had been created in the meantime.

@ScriptSmith , what do you think?
![image](https://github.com/eresearchqut/trrf/assets/60163872/2864a3db-089d-4872-8c4a-500f830c7913)

2023-08-08 23:28 UTC, ScriptSmith commented
@ppettitau Good call, new option makes sense.

2023-08-11 00:23 UTC, ppettitau commented on rdrf/report/report_configuration.py
> +                'label': 'Email Notification',
Rename to `'Email Notifications'` to keep consistent with naming of other reportable model labels

2023-08-11 00:29 UTC, ppettitau commented on rdrf/rdrf/models/definition/models.py
> +    def is_registry_subscribable(self, registries):
Not necessary, but this function name feels a bit off to me.
Can you think of anything better e.g. `any_subscribable`, `has_any_subscribable` , `has_subscribable_registry`?
Also happy for it to be left as-is.

2023-08-11 01:15 UTC, ppettitau commented on rdrf/report/schema.py
Is this `if` condition necessary? I don't think anything will break if you leave it out

2023-08-11 01:15 UTC, ppettitau commented on rdrf/report/report_configuration.py
> +                'label': 'Email Notification',
Actually, it should be `'Email Preferences'`, when thinking about it from a Patient/ User perspective, we are getting data on their email preferences, not notifications.

2023-08-11 01:15 UTC, ppettitau commented on rdrf/report/schema.py
> +    def email_notification_resolver(patient, _info):
You can resolve the EmailPreference object to be consumed by the DjangoObjectType  from here
e.g. `return EmailPreference.objects.get_by_user(patient.user)`

2023-08-11 01:15 UTC, ppettitau commented on rdrf/report/schema.py
> +    def resolve_unsubscribe_all(patient, _info):
As long as you change the resolver to resolve the EmailPreference, you can remove the lookup here and replace the `patient` parameter with the `emailPreference` object

2023-08-11 04:08 UTC, ppettitau approved these changes

2023-08-11 04:25 UTC, ScriptSmith approved these changes

2023-08-28 04:10 UTC, merged