[ERE-2181] Default consent video language to user's language
eresearchqut/trrf pull request #638
Opened 2023-08-29 05:16 UTC by Lexiel46

2023-08-29 23:49 UTC, Lexiel46 commented
To test the function, below codes should be added to the "Information text" box in a consent section. In addition, currently we have only one text track file so the src link is not changed based on language.
{% for lang in all_available_langs %}
{% if current_language.code == lang.0 or current_language.name_local == lang.1 %}
<track
      label="{{ lang.1 }}"
      kind="subtitles"
      srclang="{{ lang.0 }}"
src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/qut_subs.vtt" default />
{% else %}
<track
      label="{{ lang.1 }}"
      kind="subtitles"
      srclang="{{ lang.0 }}"
src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/qut_subs.vtt" />
{% endif %}
{% endfor %}

2023-08-30 01:06 UTC, ppettitau commented
What happens if the user selects a caption language that exists in the registry, but has no associated subtitles?
For example, I configured my local registry to support French `fr`, it generated a track for "Francais", but then when I selected it the Caption Language option disappeared. Is this expected?

_Disclaimer_ I tested the raw HTML output in the Consent Section in jsfiddle because my CSP configuration doesn't allow the Angelman video to be rendered.

1) Before selecting Francais:
![image](https://github.com/eresearchqut/trrf/assets/60163872/810d5e64-6bb9-49df-8329-c6c78048a7b9)

![image](https://github.com/eresearchqut/trrf/assets/60163872/9fd9c320-e67b-4d93-97ef-94ea3092418e)

2) After selecting Francais:
![image](https://github.com/eresearchqut/trrf/assets/60163872/0745a330-2755-495b-95a7-4e082f063e98)

2023-08-30 01:10 UTC, ppettitau commented on rdrf/rdrf/templatetags/get_info_text_expression.py
> +                    'current_language': current_lang,
Consider using consistent naming for variables. Where possible, use the same naming to represent language e.g. always either use "language" or "lang", but not a mix of both.
* all_available_langs
* current_language
* current_lang

Personally, I prefer the non-abbreviated form "language".

2023-08-30 01:56 UTC, ppettitau commented
> What happens if the user selects a caption language that exists in the registry, but has no associated subtitles? For example, I configured my local registry to support French `fr`, it generated a track for "Francais", but then when I selected it the Caption Language option disappeared. Is this expected?
> 
> _Disclaimer_ I tested the raw HTML output in the Consent Section in jsfiddle because my CSP configuration doesn't allow the Angelman video to be rendered.
> 
> 1. Before selecting Francais:
>    ![image](https://user-images.githubusercontent.com/60163872/264198401-810d5e64-6bb9-49df-8329-c6c78048a7b9.png)
> 
> ![image](https://user-images.githubusercontent.com/60163872/264198311-9fd9c320-e67b-4d93-97ef-94ea3092418e.png)
> 
> 2. After selecting Francais:
>    ![image](https://user-images.githubusercontent.com/60163872/264198350-0745a330-2755-495b-95a7-4e082f063e98.png)

I retried using proper configuration for enabling the video, and enabling the languages. It renders fine in TRRF. Sorry for the added confusion! Not sure exactly what happened the first time, but possibly didn't include the `track` rendering code as expected in the Consent Section info text.

2023-08-30 03:12 UTC, Lexiel46 commented
Changing the variable name would lead to the change of code entering into the information text box.
Please use `{% for lang in all_available_languages %}` to replace `{% for lang in all_available_langs %}`

2023-08-30 03:47 UTC, ppettitau approved these changes
Great work, Lexie :+1:

2023-08-31 11:05 UTC, ScriptSmith commented
If you use the following env variables, you can test it locally:

```
LANGUAGES="en pseudo af ar-AR zh-CN zh-TW cs fr de he hi hu id it ms pl pt ro ru es sv tr ur vi"
ENABLE_VIDEO_HOSTING=1
VIDEO_HOSTING_BASE_URL="https://d4d7dpr65gp9x.cloudfront.net/"
```

2023-08-31 11:05 UTC, ScriptSmith requested changes
Python part is great, but we need to test using a different file for different languages. I would suggest adding a file to the bucket with the same name as the language code, and using that in the template.

And as @ppettitau alluded to, missing a subtitle file with the above template would cause a 403 and leave a non-working button in the video. So we need to ensure it's available for all supported languages in the registry, or perhaps use JS to check the file exists first.

When there are a lot of languages enabled, the scrollbar in the list of subtitles is quite subtle which is annoying. Might be worth tweaking the style to make it more visible?

Also noticed that there was a 'Not same-origin' error for the default track when loading the page. Adding the `crossorigin="anonymous"` attribute to the video seemed to fix this.

2023-09-04 05:52 UTC, Lexiel46 commented
Different from previous method, there's no code to be added to template now. Instead, please at below js code to the information text box and test.
```
<script>
       var available_text_tracks = ['en', 'fr']; // Manage this array manually by checking the available text tracks in aws
      $(document).ready(function() {
          var player = videojs('TestVideo');
          var all_available_languages = {{ all_available_languages | safe }};
          var current_language = {{ current_language | safe }};
          player.ready(() => {
              for (let i = 0; i < all_available_languages.length; i++) {
                  let language = all_available_languages[i];
                  let src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language[0]}.vtt`;
                  if (available_text_tracks.includes(language[0])) {
                       player.addRemoteTextTrack({src: src, kind:'subtitles', srclang: language[0], label: language[1], default: current_language[0] == language[0] || current_language[1] == language[1]});
                  }
              }
          });
      });
</script>
```

2023-09-05 22:23 UTC, ppettitau commented
> estVideo');
>           var all_available_lang

This is very nitpicky, particularly as this JS isn't repository code, but a couple of things:
* Prefer using `const` and `let` over `var`
* Use `const` unless you are reassigning the value of the variable. 
* `src`, `current_language` is defined outside of the if condition, but it should only be assigned if we are going to use it, so move it inside the `if`.
* I don't think we gain anything by declaring `player`, this could be a one-liner

2023-09-05 22:47 UTC, Lexiel46 commented
Updated the js code as below. I think we should keep the declaration of `player` because both `player.ready` and `player.addRemoteTextTrack` require that. What do you think? @ppettitau 
```
<script>
       let available_text_tracks = ['en', 'fr']; // Manage this array manually by checking the available text tracks in aws
      $(document).ready(function() {
          let player = videojs('TestVideo');
          let all_available_languages = {{ all_available_languages | safe }};
          let current_language = {{ current_language | safe }};
          player.ready(() => {
              for (let i = 0; i < all_available_languages.length; i++) {
                  let language = all_available_languages[i];
                  if (available_text_tracks.includes(language[0])) {
                       let src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language[0]}.vtt`;
                       player.addRemoteTextTrack({src: src, kind:'subtitles', srclang: language[0], label: language[1], default: current_language[0] == language[0] || current_language[1] == language[1]});
                  }
              }
          });
      });
</script>
```

2023-09-05 23:51 UTC, ppettitau commented
> Updated the js code as below. I think we should keep the declaration of `player` because both `player.ready` and `player.addRemoteTextTrack` require that. What do you think? @ppettitau
> 
> ```
> <script>
>        const available_text_tracks = ['en', 'fr']; // Manage this array manually by checking the available text tracks in aws
>       $(document).ready(function() {
>           const player = videojs('TestVideo');
>           const all_available_languages = {{ all_available_languages | safe }};
>           const current_language = {{ current_language | safe }};
>           player.ready(() => {
>               for (let i = 0; i < all_available_languages.length; i++) {
>                   const language = all_available_languages[i];
>                   if (available_text_tracks.includes(language[0])) {
>                        const src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language[0]}.vtt`;
>                        player.addRemoteTextTrack({src: src, kind:'subtitles', srclang: language[0], label: language[1], default: current_language[0] == language[0] || current_language[1] == language[1]});
>                   }
>               }
>           });
>       });
> </script>
> ```

Looks good :+1: And yes, that makes sense - I missed that reference to the player.

2023-09-06 00:28 UTC, ScriptSmith commented
Another nitpicky thing would be to use for...of and destructuring assignment like so:

```diff
     $(document).ready(function () {
         const player = videojs('ConsentVideo');
         const all_available_languages = {{ all_available_languages | safe }};
-        const current_language = {{ current_language | safe }};
+        const [current_language_code, current_language_label] = {{ current_language | safe }};
         player.ready(() => {
-            for (let i = 0; i < all_available_languages.length; i++) {
-                const language = all_available_languages[i];
-                if (available_text_tracks.includes(language[0])) {
-                    const src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language[0]}.vtt`;
+            for (const [language_code, language_label] of all_available_languages) {
+                if (available_text_tracks.includes(language_code)) {
+                    const src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language_code}.vtt`;
                     player.addRemoteTextTrack({
                         src: src, 
                         kind: 'subtitles',
-                        srclang: language[0],
-                        label: language[1],
-                        default: current_language[0] == language[0] || current_language[1] == language[1]
+                        srclang: language_code,
+                        label: language_label,
+                        default: current_language_code === language_code || current_language_label === language_label
                     });
                 }
             }
```

I think the `||` in the `default` property is redundant too, as code should be enough for the condition.

Here's my version of the video with all the updates:
```django
<video id="ConsentVideo" class="video-js" controls preload="auto"
    poster="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/poster/consent_20220629.0000001.jpg"
    data-setup='{"fluid": true}'>
    <source src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/cmaf/consent_20220629.m3u8"
        type="application/x-mpegURL" />
    <source src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/hls/consent_20220629.m3u8"
        type="application/x-mpegURL" />
    <source src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/hls/consent_20220629.m3u8"
        type="application/x-mpegURL" />
    <source
        src="https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/mp4/consent_20220629_avc_720p.mp4"
        type="video/mp4" />
    <source src="angelman/01G6PFFT70CMQR8VS9G6W8N94C/mp4/consent_20220629_avc_480p.mp4" type="video/mp4" />
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a
        web browser that
        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
</video>

<script>
    const available_text_tracks = ['en', 'fr']; // Manage this array manually by checking the available text tracks in aws
    $(document).ready(function () {
        const player = videojs('ConsentVideo');
        const all_available_languages = {{ all_available_languages | safe }};
        const [current_language_code, current_language_label] = {{ current_language | safe }};
        player.ready(() => {
            for (const [language_code, language_label] of all_available_languages) {
                if (available_text_tracks.includes(language_code)) {
                    const src = `https://d4d7dpr65gp9x.cloudfront.net/angelman/01G6PFFT70CMQR8VS9G6W8N94C/subtitle/${language_code}.vtt`;
                    player.addRemoteTextTrack({
                        src: src, 
                        kind: 'subtitles',
                        srclang: language_code,
                        label: language_label,
                        default: current_language_code === language_code || current_language_label === language_label
                    });
                }
            }
        });
    });
</script>
```

2023-09-06 01:25 UTC, Lexiel46 commented
The `||` in the `default` property is for checking Chinese characters as our project is using `zh-CN: 简体中文` and `zh-TW: 繁體中文` for simplified Chinese and traditional Chinese while those code in Django are `zh-hans: 简体中文` and `zh-hant: 繁體中文` respectively. Hence, checking language code only is not enough in this case.

2023-09-06 06:19 UTC, ScriptSmith approved these changes

2023-09-07 23:21 UTC, merged