[ERP-695] User Activation Improvements
eresearchqut/trrf pull request #651
Opened 2023-10-18 23:49 UTC by Lexiel46

2023-11-09 23:25 UTC, ScriptSmith requested changes

2023-11-09 23:25 UTC, ScriptSmith commented on rdrf/rdrf/auth/forms.py
> +        self.fields['username'].label = 'Email Address'
Needs i18n wrapper on the string

2023-11-09 23:25 UTC, ScriptSmith commented on rdrf/rdrf/templates/registration/activate_account.html
> +        <h3>Please activate your account.</h3>
Needs `{% trans %}` tag

2023-11-09 23:25 UTC, ScriptSmith commented on rdrf/rdrf/templates/registration/activate_account.html
> +        <button class="btn btn-primary" onclick="window.open('{{ activation_url }}', '_self')">Activate my account</button>
Can this be an `<a>` element rather than a button? I think that would be more semantically correct.

2023-11-09 23:25 UTC, ScriptSmith commented on rdrf/rdrf/views/registration_rdrf.py
> +        return '%s?next=%s?new_activation=True' % (reverse("two_factor:login"), reverse("login_router"))
nit: It's technically fine to do string formatting like this, however f-strings are the more common way, rather than this 'old-style': https://realpython.com/python-string-formatting/#which-string-formatting-method-should-you-use

2023-11-09 23:25 UTC, ScriptSmith commented on rdrf/rdrf/templates/two_factor/core/login.html
> +                <div class="alert alert-success" role="alert">
Needs `{% trans %}` tag

2023-11-10 01:56 UTC, ScriptSmith approved these changes

2023-11-10 02:01 UTC, ppettitau commented on rdrf/rdrf/templates/registration/activate_account.html
> +        <p>{% trans "You are required to activate your account to gain access to the " %}{% project_title %}</p>
Maybe a blocktrans would have been better here to allow for a placeholder (project_title) that would provide better context for the string in Crowdin.

2023-11-10 02:05 UTC, ppettitau requested changes
Update `trans` tag to `blocktrans`

2023-11-10 02:53 UTC, ppettitau approved these changes

2023-11-10 03:26 UTC, merged