[ERP-520] Upgrade to Django 4
eresearchqut/trrf pull request #665
Opened 2024-01-01 21:39 UTC by ScriptSmith

2024-02-26 02:58 UTC, ppettitau requested changes
1. Date format in patient list for "Date of Birth" column differs 
    Local: 
    ![image](https://github.com/eresearchqut/trrf/assets/60163872/c7d55085-9eb3-4d52-adc1-e9ef5b307edc)
    Dev: 
    ![image](https://github.com/eresearchqut/trrf/assets/60163872/1a0dc825-0035-435f-8108-e089c74258ef)

2024-02-27 04:55 UTC, ScriptSmith commented
> 1. Date format in patient list for "Date of Birth" column differs
>        Local:
>        ![image](https://private-user-images.githubusercontent.com/60163872/307650184-c7d55085-9eb3-4d52-adc1-e9ef5b307edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDkwNDQsIm5iZiI6MTcwOTAwODc0NCwicGF0aCI6Ii82MDE2Mzg3Mi8zMDc2NTAxODQtYzdkNTUwODUtOWViMy00ZDUyLWFkYzEtZTllZjViMzA3ZWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA0MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDdlMmIzN2Y4N2QxZjk0ZmE2MmE1Y2IxMGMwZDI4MGE2ZjM0YmI0YzA2NDcwNDdlMzE0NjMzMmQwNDFiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZaIdwdIISKbG7IlARhrd_jVqZ_GfpPcbc1sJiQYApZY)
>        Dev:
>        ![image](https://private-user-images.githubusercontent.com/60163872/307650229-1a0dc825-0035-435f-8108-e089c74258ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDkwNDQsIm5iZiI6MTcwOTAwODc0NCwicGF0aCI6Ii82MDE2Mzg3Mi8zMDc2NTAyMjktMWEwZGM4MjUtMDAzNS00MzVmLTgxMDgtZTA4OWM3NDI1OGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA0MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmUwNDNhOWRkOWViM2Q3OGM4M2NjZjU5ZmU5MTdiMTI2YjVjZDIxY2FjODY2MTcyYmY0MWFhZmM3NjFkNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IzabRe7ePjt0dwXT5pnM9dVgd1Ov2mMZh-7njbNWUSQ)

:+1: I've updated the other usages of date_format except for 1 which is superficial and only visible to admins.

2024-02-27 21:45 UTC, ppettitau approved these changes

2024-03-04 01:17 UTC, Lexiel46 approved these changes

2024-03-11 02:26 UTC, merged