[ERP-780] Record user id in request logs
eresearchqut/trrf pull request #673
Opened 2024-01-25 01:31 UTC by Lexiel46

2024-02-12 04:33 UTC, ScriptSmith requested changes
uwsgi needs to be configured to log the user_id variable (ie. `--logformat`).

Also should include instructions for how to test locally for @ppettitau

2024-02-12 04:56 UTC, ScriptSmith commented on uwsgi/django.wsgi
> +    response = get_wsgi_application()(environ,start)
Do we need to call `get_wsgi_application()` each time, or can it be done once. I imagine calling django's setup each time isn't necessary?

2024-02-16 03:06 UTC, Lexiel46 commented
To test locally,
1. In `docker-compose.yml` add
`command:
      - "uwsgi"`
 to the end of `runserver`
2. In `docker-entrypoint.sh`, update ip address in `# prod uwsgi entrypoint` block
`exec uwsgi --http 0.0.0.0:8000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static --ini "${UWSGI_OPTS}"`

2024-02-18 22:22 UTC, ppettitau reviewed
![image](https://github.com/eresearchqut/trrf/assets/60163872/fb7e35e2-2487-4a7f-b65c-7031af0813cd)
Not sure why all these 404s are occurring with uwsgi enabled in `runserver`. any ideas?

2024-02-18 23:10 UTC, Lexiel46 commented
> ![image](https://private-user-images.githubusercontent.com/60163872/305750768-fb7e35e2-2487-4a7f-b65c-7031af0813cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyOTU4NTEsIm5iZiI6MTcwODI5NTU1MSwicGF0aCI6Ii82MDE2Mzg3Mi8zMDU3NTA3NjgtZmI3ZTM1ZTItMjQ4Ny00YTdmLWI2NWMtNzAzMWFmMDgxM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDIyMzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNTQxYTg5YWIwZGVjYWEwMTE3YmI4MzVlZDFlZjVjNGIxNzczN2FhZTM4MGQyYzcyZjhkMjg0YzViMTE3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adDcuSw69kVRiE-SRJwu9gjSIYwY7y0rBqwA3vI0v0k) Not sure why all these 404s are occurring with uwsgi enabled in `runserver`. any ideas?

I had similar issue at first but it was fixed somehow by itself. But I still get error
`GET http://localhost:8000/static/js/vendor/jquery-3.5.1.min.js net::ERR_ABORTED 404 (Not Found)`
![image](https://github.com/eresearchqut/trrf/assets/139732653/2c1cc42c-11dc-4b45-a5c7-a1c43fdcf41e)

2024-02-22 23:47 UTC, ScriptSmith commented
You also need to run `collectstatic`:

```
diff --git a/docker/dev/docker-entrypoint.sh b/docker/dev/docker-entrypoint.sh
index 05b420b9..502d988e 100755
--- a/docker/dev/docker-entrypoint.sh
+++ b/docker/dev/docker-entrypoint.sh
@@ -176,10 +176,11 @@ if [ "$1" = 'uwsgi' ]; then
     info "[Run] Starting prod uwsgi"
 
     _django_check_deploy
+    django-admin collectstatic --noinput --settings="${DJANGO_SETTINGS_MODULE}" 2>&1
 
     set -x
     # exec uwsgi --die-on-term --ini "${UWSGI_OPTS}"
-    exec uwsgi --http :9000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static --ini "${UWSGI_OPTS}"
+    exec uwsgi --http 0.0.0.0:8000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static --ini "${UWSGI_OPTS}"
 fi
```

2024-02-27 02:10 UTC, ScriptSmith requested changes

2024-02-27 02:10 UTC, ScriptSmith commented on docker/dev/docker-entrypoint.sh
> -    exec uwsgi --http :9000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static
To apply this in AWS, we need to make this same change in `uwsgi_ssl_fargate`

2024-02-27 02:10 UTC, ScriptSmith commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
Can we get the app only once?

2024-02-27 02:10 UTC, ScriptSmith commented on uwsgi/django.wsgi
>      for key in environ:
Does anything break if we remove this? What is origin / purpose of this?

2024-02-27 02:10 UTC, ScriptSmith commented on docker/dev/docker-entrypoint.sh
> -    exec uwsgi --http :9000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static
Not necessarily a problem, but for either of you does uwsgi allocate 8gb of memory when run like this? I imagine it wouldn't on resource-constrained servers like in AWS, but I thought it was a little strange.

2024-02-27 05:24 UTC, Lexiel46 commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
> Can we get the app only once?

Tried to move `app` out of `application` but got `Internal Server Error`

2024-02-27 05:24 UTC, Lexiel46 commented on uwsgi/django.wsgi
>      for key in environ:
> Does anything break if we remove this? What is origin / purpose of this?

I think it is to make these variables accessible through `os.environ` within the Python script. But I recken 
Below are how the `keys` in `environ` looks like:
"""
REQUEST_METHOD
REQUEST_URI
PATH_INFO
QUERY_STRING
SERVER_PROTOCOL
SCRIPT_NAME
SERVER_NAME
SERVER_PORT
UWSGI_ROUTER
REMOTE_ADDR
REMOTE_PORT
HTTP_HOST
HTTP_CONNECTION
HTTP_SEC_CH_UA
HTTP_SEC_CH_UA_MOBILE
HTTP_USER_AGENT
HTTP_SEC_CH_UA_PLATFORM
HTTP_ACCEPT
HTTP_SEC_FETCH_SITE
HTTP_SEC_FETCH_MODE
HTTP_SEC_FETCH_DEST
HTTP_REFERER
HTTP_ACCEPT_ENCODING
HTTP_ACCEPT_LANGUAGE
HTTP_COOKIE
wsgi.input
wsgi.file_wrapper
wsgi.version
wsgi.errors
wsgi.run_once
wsgi.multithread
wsgi.multiprocess
wsgi.url_scheme
uwsgi.version
uwsgi.node
"""

2024-02-27 22:33 UTC, Lexiel46 commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
Did another try to move `uwsgi.workers()` out from the function, then no value for the key `apps` in the worker. Print out the worker shows
"""
{'id': 0, 'pid': 0, 'requests': 0, 'delta_requests': 0, 'signals': 0, 'exceptions': 0, 'status': b'idle', 'rss': 0, 'vsz': 0, 'running_time': 0, 'last_spawn': 0, 'respawn_count': 18446744073709551615, 'tx': 0, 'avg_rt': 0, 'apps': ()}
"""
While when `uwsgi.workers()` is called in the `application` function, the result is like
"""
{'id': 1, 'pid': 33, 'requests': 0, 'delta_requests': 0, 'signals': 0, 'exceptions': 0, 'status': b'busy', 'rss': 0, 'vsz': 0, 'running_time': 0, 'last_spawn': 1709072816, 'respawn_count': 0, 'tx': 0, 'avg_rt': 0, 'apps': ({'id': 0, 'modifier1': 0, 'mountpoint': b'', 'startup_time': 0, 'interpreter': 94409031401856, 'callable': 140562906154032, 'requests': 1, 'exceptions': 0, 'chdir': b''},)}
"""

2024-02-29 23:19 UTC, ScriptSmith commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
Ok :+1:. We could try using a global variable, but I don't know it would be that much faster

2024-02-29 23:19 UTC, ScriptSmith commented on uwsgi/django.wsgi
>      for key in environ:
Do any of the end2end tests fail if it's removed?

2024-03-01 04:54 UTC, Lexiel46 commented on uwsgi/django.wsgi
>      for key in environ:
Tested by removing the `for loop`  >  run `docker compose build` > run `./scripts/update-test-zips.sh` > run `./scripts/end2end-tests.sh` , no error detected. Given no errors pop up, I guess we can remove it. What do you think? @ScriptSmith

2024-03-04 00:45 UTC, Lexiel46 commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
Comparison between with global variable and without was conducted twice by running `time curl 0.0.0.0:8000` , and both results showing there's no big difference in between.
![Screenshot from 2024-03-04 10-44-05](https://github.com/eresearchqut/trrf/assets/139732653/8f0ebbba-e3d1-4f97-86c6-9a860b70ea92)

2024-03-04 06:15 UTC, ScriptSmith requested changes

2024-03-04 06:15 UTC, ScriptSmith commented on uwsgi/django.wsgi
>      for key in environ:
Looking at the git history I can't understand why this was done either. I think try it out in dev and if anything breaks we can revert it.

2024-03-04 06:15 UTC, ScriptSmith commented on uwsgi/django.wsgi
> +    uwsgi.set_logvar('app', str(app))
Yeah lets leave it as is

2024-03-05 02:19 UTC, ScriptSmith approved these changes

2024-03-05 02:47 UTC, ppettitau commented on docker/dev/docker-entrypoint.sh
> -    exec uwsgi --http :9000 --wsgi-file /app/uwsgi/django.wsgi --static-map /static=/data/static
No, not for me.
![image](https://github.com/eresearchqut/trrf/assets/60163872/7fdaed0c-112c-453b-93a1-6d8167a21d1a)

2024-03-05 02:47 UTC, ppettitau approved these changes

2024-03-05 04:34 UTC, merged