[ERP-2589] Changes to Demographics Page - Working Groups
eresearchqut/trrf pull request #710
Opened 2024-10-03 01:04 UTC by ppettitau

* Split working groups into multiple fields based on working group type
* Add CSS to enable all multi selects to be resizable.

2024-10-11 02:09 UTC, ScriptSmith requested changes
There's an issue with reporting on the working group types of registries that don't have any working group types.

2024-10-11 02:09 UTC, ScriptSmith commented on rdrf/rdrf/helpers/form_section_helper.py
> +                if "working_groups_" in field
nit: `startswith` rather than `in` here and elsewhere

2024-10-13 23:10 UTC, ppettitau commented on rdrf/rdrf/helpers/form_section_helper.py
> +                if "working_groups_" in field
Fixed.

Also fixed the issue with reporting not working when there are no working group types.

2024-10-14 02:54 UTC, ScriptSmith approved these changes

2024-10-14 03:01 UTC, merged